List<Map<String, dynamic>> posts = [
  {
    "username": "Alice",
    "location": "Manila, Philippines",
    "profileImage": "https://randomuser.me/api/portraits/women/44.jpg",
    "restaurant": "Ichiran Ramen",
    "restaurantImages": [
      "https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg",
      "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg",
    ],
    "caption": "Best ramen I’ve had 🍜🔥",
    "rating": 4.7,
    "hearts": 123,
    "isLiked": false,
    "comment": "",
    "timeAgo": "2h ago",
  },
  {
    "username": "Bob",
    "location": "Cebu City",
    "profileImage": "https://randomuser.me/api/portraits/men/36.jpg",
    "restaurant": "Lantaw Native Restaurant",
    "restaurantImages": [
      "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg",
      "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
    ],
    "caption": "Chill vibes, good food 😋",
    "rating": 4.3,
    "hearts": 98,
    "isLiked": false,
    "comment": "",
    "timeAgo": "5h ago",
  },
  {
    "username": "Carla",
    "location": "Davao City",
    "profileImage": "https://randomuser.me/api/portraits/women/65.jpg",
    "restaurant": "Yellow Fin Seafood",
    "restaurantImages": [
      "https://images.pexels.com/photos/4210859/pexels-photo-4210859.jpeg",
      "https://images.pexels.com/photos/3296273/pexels-photo-3296273.jpeg",
    ],
    "caption": "Fresh seafood, highly recommended 🐟🦐",
    "rating": 4.8,
    "hearts": 650,
    "isLiked": false,
    "comment": "",
    "timeAgo": "1d ago",
  },
  {
    "username": "Daniel",
    "location": "Quezon City",
    "profileImage": "https://randomuser.me/api/portraits/men/22.jpg",
    "restaurant": "Burger Shack",
    "restaurantImages": [
      "https://images.pexels.com/photos/1639567/pexels-photo-1639567.jpeg",
    ],
    "caption": "Burgers were okay, but kinda dry 🍔",
    "rating": 3.5,
    "hearts": 54,
    "isLiked": false,
    "comment": "",
    "timeAgo": "3d ago",
  },
  {
    "username": "Ella",
    "location": "Taguig",
    "profileImage": "https://randomuser.me/api/portraits/women/12.jpg",
    "restaurant": "Sushi Express",
    "restaurantImages": [
      "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg",
      "https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg",
    ],
    "caption": "Too much rice, less fish 🍣😕",
    "rating": 2.8,
    "hearts": 37,
    "isLiked": false,
    "comment": "",
    "timeAgo": "5d ago",
  },
  {
    "username": "Frank",
    "location": "Makati",
    "profileImage": "https://randomuser.me/api/portraits/men/77.jpg",
    "restaurant": "Pizza Town",
    "restaurantImages": [
      "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
    ],
    "caption": "Pizza was cold when served 🍕❄️",
    "rating": 3.2,
    "hearts": 80,
    "isLiked": false,
    "comment": "",
    "timeAgo": "1w ago",
  },
];
