// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyWY0aGf1R4CZem4jgFJHD13JubSyPXg',
    appId: '1:1095712201757:web:bbcf66a2dfe7977022faf4',
    messagingSenderId: '1095712201757',
    projectId: 'foodtrackingvii',
    authDomain: 'foodtrackingvii.firebaseapp.com',
    storageBucket: 'foodtrackingvii.firebasestorage.app',
    measurementId: 'G-P3ZB3XQ1DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpDZ0xEcUQ_1tANspyViaMLjgNcpWbLY',
    appId: '1:1095712201757:android:e804e559f073277c22faf4',
    messagingSenderId: '1095712201757',
    projectId: 'foodtrackingvii',
    storageBucket: 'foodtrackingvii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD_x-5RZpEDjzW_WHFzyhnUQ5tFMaEAFY',
    appId: '1:1095712201757:ios:4b5d1611cd5a57be22faf4',
    messagingSenderId: '1095712201757',
    projectId: 'foodtrackingvii',
    storageBucket: 'foodtrackingvii.firebasestorage.app',
    iosBundleId: 'com.example.foodtrackerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD_x-5RZpEDjzW_WHFzyhnUQ5tFMaEAFY',
    appId: '1:1095712201757:ios:4b5d1611cd5a57be22faf4',
    messagingSenderId: '1095712201757',
    projectId: 'foodtrackingvii',
    storageBucket: 'foodtrackingvii.firebasestorage.app',
    iosBundleId: 'com.example.foodtrackerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJyWY0aGf1R4CZem4jgFJHD13JubSyPXg',
    appId: '1:1095712201757:web:a50e906faf09443522faf4',
    messagingSenderId: '1095712201757',
    projectId: 'foodtrackingvii',
    authDomain: 'foodtrackingvii.firebaseapp.com',
    storageBucket: 'foodtrackingvii.firebasestorage.app',
    measurementId: 'G-REDZMP0BTB',
  );

}