// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVWoRgPwiPBXSDPeIgwalbI1JJxfSKi8',
    appId: '1:413421746127:web:a08890a59eec0f8f0e44ba',
    messagingSenderId: '413421746127',
    projectId: 'foodtracktester',
    authDomain: 'foodtracktester.firebaseapp.com',
    storageBucket: 'foodtracktester.firebasestorage.app',
    measurementId: 'G-PDH6X062ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6KBMdU3dr0BUKnJYUU6pwtvvjoGvGqTI',
    appId: '1:413421746127:android:b5cf56e1afc503db0e44ba',
    messagingSenderId: '413421746127',
    projectId: 'foodtracktester',
    storageBucket: 'foodtracktester.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMoQyI3rlmAnSE2MbUPDmwhrhwcgMl5I',
    appId: '1:413421746127:ios:77d0c1dfcfcebbbf0e44ba',
    messagingSenderId: '413421746127',
    projectId: 'foodtracktester',
    storageBucket: 'foodtracktester.firebasestorage.app',
    iosBundleId: 'com.example.foodtrackerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfMoQyI3rlmAnSE2MbUPDmwhrhwcgMl5I',
    appId: '1:413421746127:ios:77d0c1dfcfcebbbf0e44ba',
    messagingSenderId: '413421746127',
    projectId: 'foodtracktester',
    storageBucket: 'foodtracktester.firebasestorage.app',
    iosBundleId: 'com.example.foodtrackerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsVWoRgPwiPBXSDPeIgwalbI1JJxfSKi8',
    appId: '1:413421746127:web:43dc0e39e2a84f4a0e44ba',
    messagingSenderId: '413421746127',
    projectId: 'foodtracktester',
    authDomain: 'foodtracktester.firebaseapp.com',
    storageBucket: 'foodtracktester.firebasestorage.app',
    measurementId: 'G-KZ6Z27RME4',
  );

}