// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6G2bjylcqCrsD_g5bg99_LnlEwb_32CE',
    appId: '1:444989021729:web:1d310ca33baf9caeca8d60',
    messagingSenderId: '444989021729',
    projectId: 'foodtracking106l',
    authDomain: 'foodtracking106l.firebaseapp.com',
    storageBucket: 'foodtracking106l.firebasestorage.app',
    measurementId: 'G-MSYT1E4QR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdQZzE7hiIJWG14tY0ASmFjTTTaD849Zs',
    appId: '1:444989021729:android:a94923e8c72edc02ca8d60',
    messagingSenderId: '444989021729',
    projectId: 'foodtracking106l',
    storageBucket: 'foodtracking106l.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBqq1izXPm6FJEyGyIYki0MqhKxkK0S0',
    appId: '1:444989021729:ios:271a165e4af4c79aca8d60',
    messagingSenderId: '444989021729',
    projectId: 'foodtracking106l',
    storageBucket: 'foodtracking106l.firebasestorage.app',
    iosBundleId: 'com.example.foodtrackerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBqq1izXPm6FJEyGyIYki0MqhKxkK0S0',
    appId: '1:444989021729:ios:271a165e4af4c79aca8d60',
    messagingSenderId: '444989021729',
    projectId: 'foodtracking106l',
    storageBucket: 'foodtracking106l.firebasestorage.app',
    iosBundleId: 'com.example.foodtrackerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6G2bjylcqCrsD_g5bg99_LnlEwb_32CE',
    appId: '1:444989021729:web:415cca9132578d34ca8d60',
    messagingSenderId: '444989021729',
    projectId: 'foodtracking106l',
    authDomain: 'foodtracking106l.firebaseapp.com',
    storageBucket: 'foodtracking106l.firebasestorage.app',
    measurementId: 'G-GZ6EBFE8W3',
  );

}